### ISSUE TITLE
Bob encryption not worked:(

### ISSUE THREAD

**Issue by d954mas** [defold/extension-resource-encryption#1]
1)I make copy of this estension
https://github.com/defold/extension-resource-encryption

2)I set key to "GAZVwlJL0W6U874e". In bob and in c++. But i have error when start game.

3)When i set c++ key to default "aQj8CScgNP4VsfXK" it worked.

I update plugin.Also i checked it decompiled version.

![2023-04-06_20-37-46](https://user-images.githubusercontent.com/2655263/230456189-df88b75d-d055-4505-9e5f-a01a2a726d49.png)

**Comment by d954mas** [comment]
1)Bob use new KEY: "GAZVwlJL0W6U874e"
https://github.com/d954mas/extension-resource-encryption/blob/c9e2551b45cc7450f6d8b29a4e0a0df17c988a0c/resourceencryption/pluginsrc/com/dynamo/bob/archive/CustomResourceEncryption.java#L5
2)C++ use default KEY: https://github.com/d954mas/extension-resource-encryption/blob/c9e2551b45cc7450f6d8b29a4e0a0df17c988a0c/resourceencryption/src/plugin.cpp#L7

If you try bundle game will worked.

---

If you set c++ key to  "GAZVwlJL0W6U874e" the game will be crashed

**Comment by d954mas** [comment]
Another question. I need to make repository? Can i just copy resourceencryption folder in root of project?

**Comment by d954mas** [comment]
Thanks. What i am doing wrong?

**Comment by d954mas** [comment]
In game.project 
```
[library]
include_dirs = sillyencryption
```
But folder with code have name resourceencryption

**Comment by britzl** [comment]
> I need to make repository? Can i just copy resourceencryption folder in root of project?

It's enough to copy the folder into your project.

> Thanks. What i am doing wrong?

Not sure yet. I'll have to check after the easter holiday.

**Comment by d954mas** [comment]
Missed  package in jave file 
`package com.dynamo.bob.archive;`
